routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', 'HomeController@index')->name('home');

Route::group(['prefix' => '@{username}', 'as' => 'user.'], function () {
    Route::get('', 'UserController@done')->name('done');
    Route::get('pending', 'UserController@pending')->name('pending');
    Route::get('products', 'UserController@products')->name('products');
    Route::get('questions', 'UserController@questions')->name('questions');
    Route::get('answers', 'UserController@answers')->name('answers');
    Route::get('following', 'UserController@following')->name('following');
    Route::get('followers', 'UserController@followers')->name('followers');
});

Route::group(['prefix' => 'settings', 'as' => 'user.settings.', 'middleware' => ['auth', 'password.confirm']], function () {
    Route::get('', 'UserController@profileSettings')->name('profile');
    Route::get('account', 'UserController@accountSettings')->name('account');
    Route::get('password', 'UserController@passwordSettings')->name('password');
    Route::get('notifications', 'UserController@notificationsSettings')->name('notifications');
    Route::get('delete', 'UserController@deleteSettings')->name('delete');
});

Route::get('login/{provider}', 'SocialController@redirect');
Route::get('login/{provider}/callback', 'SocialController@Callback');

Route::group(['prefix' => 'product/{slug}', 'as' => 'product.'], function () {
    Route::get('', 'ProductController@done')->name('done');
    Route::get('pending', 'ProductController@pending')->name('pending');
    Route::get('edit', 'ProductController@edit')->name('edit')->middleware('auth');
});

Route::group(['prefix' => 'products', 'as' => 'products.'], function () {
    Route::get('', 'ProductController@newest')->name('newest');
    Route::get('launched', 'ProductController@launched')->name('launched');
    Route::get('new', 'ProductController@new')->name('new')->middleware('auth');
});

Route::group(['prefix' => 'questions', 'as' => 'questions.'], function () {
    Route::get('', 'QuestionController@newest')->name('newest');
    Route::get('unanswered', 'QuestionController@unanswered')->name('unanswered');
    Route::get('popular', 'QuestionController@popular')->name('popular');
    Route::get('new', 'QuestionController@new')->name('new')->middleware('auth');
});

Route::group(['prefix' => 'question', 'as' => 'question.'], function () {
    Route::get('{id}', 'QuestionController@question')->name('question');
    Route::get('edit/{id}', 'QuestionController@edit')->name('edit')->middleware('auth');
});

Route::group(['prefix' => 'notifications', 'as' => 'notifications.', 'middleware' => ['auth']], function () {
    Route::get('', 'NotificationController@unread')->name('unread');
    Route::get('all', 'NotificationController@all')->name('all');
});

// Toggles
Route::get('adminbar', 'Admin\AdminBarController@toggle')->name('adminbar')->middleware(['auth', 'staff']);
Route::get('darkmode', 'UserController@darkMode')->name('darkmode')->middleware('patron');

Route::get('task/{id}', 'TaskController@task')->name('task');

Route::get('tasks', 'TaskController@tasks')->name('tasks')->middleware('auth');

Route::get('patron', 'PatronController@patron')->name('patron');

Route::personalDataExports('personal-data-exports');

Route::get('streaks/{username}', 'StatsController@streaks')->name('streak');

app/Http/Controllers/NotificationController.php
<?php

namespace App\Http\Controllers;

class NotificationController extends Controller
{
    public function unread()
    {
        return view('notifications.unread');
    }

    public function all()
    {
        return view('notifications.all');
    }
}

app/Http/Livewire/Admin/Adminbar.php
<?php

namespace App\Http\Livewire\Admin;

use App\Answer;
use App\AnswerPraise;
use App\Product;
use App\Question;
use App\QuestionPraise;
use App\Task;
use App\TaskComment;
use App\TaskCommentPraise;
use App\TaskPraise;
use App\User;
use Illuminate\Support\Facades\File;
use Livewire\Component;

class Adminbar extends Component
{
    protected $listeners = [
        'refreshStats' => 'render',
    ];

    public function refreshStats()
    {
        $this->emitSelf('refreshStats');
    }

    public function render()
    {
        if (file_exists('../.git/HEAD')) {
            $branch = File::get('../.git/HEAD');
            $explodedstring = explode('/', $branch, 3);
            $branchname = str_replace("\n", '', $explodedstring[2]);
        } else {
            $branchname = 'master';
        }
        if (file_exists('../VERSION')) {
            $version = File::get('../VERSION');
        } else {
            $version = '0.0.0';
        }

        // DB Details
        $tasks = Task::cacheFor(60 * 60)->count();
        $users = User::cacheFor(60 * 60)->count();
        $products = Product::cacheFor(60 * 60)->count();
        $reputations = User::cacheFor(60 * 60)->sum('reputation');
        $questions = Question::cacheFor(60 * 60)->count();
        $answers = Answer::cacheFor(60 * 60)->count();
        $comments = TaskComment::cacheFor(60 * 60)->count();
        $praises =
            TaskPraise::count() +
            TaskCommentPraise::count() +
            QuestionPraise::count() +
            AnswerPraise::count();

        return view('livewire.admin.adminbar', [
            'version' => $version,
            'branchname' => $branchname,
            'tasks' => $tasks,
            'users' => $users,
            'products' => $products,
            'reputations' => $reputations,
            'questions' => $questions,
            'answers' => $answers,
            'comments' => $comments,
            'praises' => $praises,
        ]);
    }
}

app/Http/Livewire/Answer/Answers.php
<?php

namespace App\Http\Livewire\Answer;

use App\Answer;
use Illuminate\Pagination\LengthAwarePaginator;
use Illuminate\Pagination\Paginator;
use Illuminate\Support\Collection;
use Livewire\Component;

class Answers extends Component
{
    public $listeners = [
        'answerAdded' => 'render',
        'answerDeleted' => 'render',
    ];

    public $question;
    public $page;
    public $perPage;

    public function mount($question, $page, $perPage)
    {
        $this->question = $question;
        $this->page = $page ? $page : 1;
        $this->perPage = $perPage ? $perPage : 1;
    }

    public function paginate($items, $options = [])
    {
        $page = $this->page ?: (Paginator::resolveCurrentPage() ?: 1);
        $items = $items instanceof Collection ? $items : Collection::make($items);

        return new LengthAwarePaginator($items->forPage($page, $this->perPage), $items->count(), $this->perPage, $page, $options);
    }

    public function render()
    {
        $answers = Answer::cacheFor(60 * 60)
            ->where('question_id', $this->question->id)
            ->orderBy('created_at', 'DESC')
            ->get();

        return view('livewire.answer.answers', [
            'answers' => $this->paginate($answers),
            'page' => $this->page,
        ]);
    }
}

app/Http/Livewire/Answer/CreateAnswer.php
<?php

namespace App\Http\Livewire\Answer;

use App\Answer;
use App\Gamify\Points\CommentCreated;
use App\Notifications\Answered;
use Auth;
use Livewire\Component;

class CreateAnswer extends Component
{
    public $answer;
    public $question;

    public function mount($question)
    {
        $this->question = $question;
    }

    public function updated($field)
    {
        if (Auth::check()) {
            $this->validateOnly($field, [
                'answer' => 'required|profanity',
            ],
            [
                'answer.profanity' => 'Please check your words!',
            ]);
        } else {
            session()->flash('error', 'Forbidden!');
        }
    }

    public function submit()
    {
        if (Auth::check()) {
            $validatedData = $this->validate([
                'answer' => 'required|profanity',
            ],
            [
                'answer.profanity' => 'Please check your words!',
            ]);

            if (Auth::user()->isFlagged) {
                return session()->flash('error', 'Your account is flagged!');
            }

            $answer = Answer::create([
                'user_id' =>  Auth::id(),
                'question_id' =>  $this->question->id,
                'answer' => $this->answer,
            ]);

            $this->emit('answerAdded');
            $this->answer = '';

            if (Auth::id() !== $this->question->user->id) {
                $this->question->user->notify(new Answered($answer));
                givePoint(new CommentCreated($answer));
            }

            return session()->flash('success', 'Answer has been added!');
        } else {
            session()->flash('error', 'Forbidden!');
        }
    }

    public function render()
    {
        return view('livewire.answer.create-answer');
    }
}

app/Http/Livewire/Answer/LoadMore.php
<?php

namespace App\Http\Livewire\Answer;

use App\Answer;
use Illuminate\Pagination\LengthAwarePaginator;
use Illuminate\Pagination\Paginator;
use Illuminate\Support\Collection;
use Livewire\Component;

class LoadMore extends Component
{
    public $question;
    public $page;
    public $perPage;
    public $loadMore;

    public function mount($question, $page, $perPage)
    {
        $this->question = $question;
        $this->page = $page + 1; //increment the page
        $this->perPage = $perPage;
        $this->loadMore = false; //show the button
    }

    public function paginate($items, $options = [])
    {
        $page = $this->page ?: (Paginator::resolveCurrentPage() ?: 1);
        $items = $items instanceof Collection ? $items : Collection::make($items);

        return new LengthAwarePaginator($items->forPage($page, $this->perPage), $items->count(), $this->perPage, $page, $options);
    }

    public function loadMore()
    {
        $this->loadMore = true;
    }

    public function render()
    {
        if ($this->loadMore) {
            $answers = Answer::cacheFor(60 * 60)
                ->where('question_id', $this->question->id)
                ->get();

            return view('livewire.answer.answers', [
                'answers' => $this->paginate($answers),
            ]);
        } else {
            return view('livewire.load-more');
        }
    }
}

app/Http/Livewire/Answer/SingleAnswer.php
<?php

namespace App\Http\Livewire\Answer;

use App\AnswerPraise;
use App\Gamify\Points\PraiseCreated;
use App\Notifications\AnswerPraised;
use Auth;
use Livewire\Component;

class SingleAnswer extends Component
{
    public $answer;
    public $confirming;

    public function mount($answer)
    {
        $this->answer = $answer;
    }

    public function togglePraise()
    {
        if (Auth::check()) {
            if (Auth::user()->isFlagged) {
                return session()->flash('error', 'Your account is flagged!');
            }
            if (Auth::id() === $this->answer->user->id) {
                return session()->flash('error', 'You can\'t praise your own answer!');
            }
            $isPraised = AnswerPraise::where([
                ['user_id', Auth::id()],
                ['answer_id', $this->answer->id],
            ])->count();
            if ($isPraised === 1) {
                $praise = AnswerPraise::where([
                    ['user_id', Auth::id()],
                    ['answer_id', $this->answer->id],
                ])->first();
                $praise->delete();
                $this->answer->refresh();
            } else {
                $praise = AnswerPraise::create([
                    'user_id' => Auth::id(),
                    'answer_id' => $this->answer->id,
                ]);
                $this->answer->refresh();
                $this->answer->user->notify(new AnswerPraised($this->answer, Auth::id()));
                givePoint(new PraiseCreated($praise));
            }
        } else {
            return session()->flash('error', 'Forbidden!');
        }
    }

    public function confirmDelete()
    {
        $this->confirming = $this->answer->id;
    }

    public function deleteAnswer()
    {
        if (Auth::check()) {
            if (Auth::user()->isFlagged) {
                return session()->flash('error', 'Your account is flagged!');
            }

            if (Auth::user()->staffShip or Auth::id() === $this->answer->user->id) {
                $this->answer->delete();
                $this->emit('answerDeleted');
            } else {
                session()->flash('error', 'Forbidden!');
            }
        } else {
            return session()->flash('error', 'Forbidden!');
        }
    }

    public function render()
    {
        return view('livewire.answer.single-answer');
    }
}

app/Http/Livewire/Home/LoadMore.php
<?php

namespace App\Http\Livewire\Home;

use App\Task;
use Auth;
use Carbon\Carbon;
use Illuminate\Pagination\LengthAwarePaginator;
use Illuminate\Pagination\Paginator;
use Illuminate\Support\Collection;
use Livewire\Component;

class LoadMore extends Component
{
    public $listeners = [
        'taskAdded' => 'render',
    ];

    public $page;
    public $perPage;
    public $loadMore;

    public function mount($page = 1, $perPage = 1)
    {
        $this->page = $page + 1; //increment the page
        $this->perPage = $perPage;
        $this->loadMore = false; //show the button
    }

    public function paginate($items, $options = [])
    {
        $page = $this->page ?: (Paginator::resolveCurrentPage() ?: 1);
        $items = $items instanceof Collection ? $items : Collection::make($items);

        return new LengthAwarePaginator($items->forPage($page, $this->perPage), $items->count(), $this->perPage, $page, $options);
    }

    public function loadMore()
    {
        $this->loadMore = true;
    }

    public function render()
    {
        if ($this->loadMore) {
            $user = Auth::user();
            if (Auth::check() && $user->onlyFollowingsTasks) {
                $userIds = $user->followings->pluck('id');
                $userIds->push(Auth::id());
                $tasks = Task::cacheFor(60 * 60)
                    ->select('id', 'task', 'done', 'done_at', 'user_id')
                    ->whereIn('user_id', $userIds)
                    ->where('done', true)
                    ->orderBy('done_at', 'desc')
                    ->get()
                    ->groupBy(function ($date) {
                        return Carbon::parse($date->done_at)->format('d-M-y');
                    });
            } else {
                $tasks = Task::cacheFor(60 * 60)
                    ->select('id', 'task', 'done', 'done_at', 'user_id')
                    ->where('done', true)
                    ->orderBy('done_at', 'desc')
                    ->get()
                    ->groupBy(function ($date) {
                        return Carbon::parse($date->done_at)->format('d-M-y');
                    });
            }

            return view('livewire.home.tasks', [
                'tasks' => $this->paginate($tasks),
            ]);
        } else {
            return view('livewire.load-more');
        }
    }
}

app/Http/Livewire/Home/Onboarding.php
<?php

namespace App\Http\Livewire\Home;

use Auth;
use Livewire\Component;

class Onboarding extends Component
{
    public function calculateCompleteness($task_count, $praise_count, $product_count, $has_name)
    {
        $completed = [];

        if ($task_count !== 0) {
            array_push($completed, 'task_count');
        }

        if ($praise_count !== 0) {
            array_push($completed, 'task_count');
        }

        if ($product_count !== 0) {
            array_push($completed, 'task_count');
        }

        if (strlen($has_name) !== 0) {
            array_push($completed, 'has_name');
        }

        return count($completed);
    }

    public function render()
    {
        $task_count = Auth::user()->tasks->count();
        $praise_count = Auth::user()->task_praise->count();
        $product_count = Auth::user()->products->count();
        $has_name = Auth::user()->firstname;
        $changed_username = preg_match('/^[a-f0-9]{32}$/', Auth::user()->username);
        $completed = $this->calculateCompleteness(
                        $task_count,
                        $praise_count,
                        $product_count,
                        $has_name,
                    );

        return view('livewire.home.onboarding', [
            'task_count' => $task_count,
            'praise_count' => $praise_count,
            'product_count' => $product_count,
            'has_name' => $has_name,
            'changed_username' => $changed_username,
            'completed' => $completed,
        ]);
    }
}

app/Http/Livewire/Notification/Delete.php
<?php

namespace App\Http\Livewire\Notification;

use Auth;
use Livewire\Component;

class Delete extends Component
{
    public function deleteAll()
    {
        Auth::user()->notifications()->delete();
        $this->emit('deleteAll');
    }

    public function render()
    {
        return view('livewire.notification.delete');
    }
}

app/Http/Livewire/Notification/Icon.php
<?php

namespace App\Http\Livewire\Notification;

use Livewire\Component;

class Icon extends Component
{
    public function render()
    {
        return view('livewire.notification.icon');
    }
}

resources/views/livewire/notification/all.blade.php
<div>
    @if ($notifications->count() === 0)
    <div class="card-body text-center mt-5">
        <i class="fa fa-4x fa-bell mb-3 text-primary"></i>
        <div class="h4">
            No notifications
        </div>
    </div>
    @endif
    @foreach ($notifications as $notification)
        <div wire:poll>
            @livewire('notification.single-notification', [
                'type' => $notification->type,
                'data' => $notification->data,
                'created_at' => $notification->created_at,
            ], key($notification->id))
        </div>
    @endforeach
    @if ($notifications->hasMorePages())
        @livewire('notification.load-more', [
            'type' => 'all',
            'page' => $page,
            'perPage' => $perPage
        ])
    @endif
</div>

resources/views/livewire/notification/delete.blade.php
<button class="btn btn-danger float-md-right mb-3" wire:click="deleteAll">
    <i class="fa fa-trash-alt mr-1"></i>
    Delete all Notification
    <span wire:target="deleteAll" wire:loading class="spinner-border spinner-border-sm ml-2" role="status"></span>
</button>

resources/views/livewire/notification/follow.blade.php
<div>
    @if (Auth::user()->isFollowing($user))
    <button wire:click="followUser" wire:loading.attr="disabled" class="btn btn-sm btn-danger">
        <i class="fa fa-user-minus mr-1"></i>
        Unfollow <span class="font-weight-bold">{{ '@'.$user->username }}</span>
    </button>
    @else
    <button wire:click="followUser" wire:loading.attr="disabled" class="btn btn-sm btn-primary">
        <i class="fa fa-user-plus mr-1"></i>
        Follow back <span class="font-weight-bold">{{ '@'.$user->username }}</span>
    </button>
    @endif
    @if (session()->has('error'))
        <span class="ml-2 text-danger font-weight-bold">{{ session('error') }}</span>
    @endif
</div>

resources/views/livewire/notification/icon.blade.php
<li wire:poll.5s class="nav-item mr-2">
    <a class="nav-link text-white" href="{{ route('notifications.unread') }}">
        {{ Emoji::bell() }}
        @auth
        @if (Auth::user()->unreadNotifications->count() !== 0)
        <span class="notification-count bg-danger font-weight-bold rounded">
            {{ Auth::user()->unreadNotifications->count() }}
        </span>
        @endif
        @endauth
    </a>
</li>

resources/views/livewire/notification/load-more.blade.php
<div>
    {{-- A good traveler has no fixed plans and is not intent upon arriving. --}}
</div>

resources/views/livewire/notification/mark-as-read.blade.php
<button class="btn btn-success text-white float-md-right mb-3" wire:click="markAsRead">
    <i class="fa fa-check mr-1"></i>
    Mark all as Read
    <span wire:target="markAsRead" wire:loading class="spinner-border spinner-border-sm ml-2" role="status"></span>
</button>

resources/views/livewire/notification/single-notification.blade.php
<div>
    @php
        $user = \App\User::find($data['user_id']);
    @endphp
    <div class="card mb-3">
        <div class="card-body">
            <span class="font-weight-bold">
                @if (
                    $type === "App\Notifications\TaskPraised" or
                    $type === "App\Notifications\QuestionPraised" or
                    $type === "App\Notifications\AnswerPraised" or
                    $type === "App\Notifications\TaskCommentPraised"
                )
                    {{ Emoji::clappingHands() }}
                @elseif ($type === "App\Notifications\TaskMentioned")
                    {{ Emoji::raisedHand() }}
                @elseif (
                    $type === "App\Notifications\Followed" or
                    $type === "App\Notifications\Subscribed"
                )
                    {{ Emoji::plusSign() }}
                @elseif (
                    $type === "App\Notifications\TaskCommented" or
                    $type === "App\Notifications\Answered"
                )
                    {{ Emoji::speechBalloon() }}
                @endif
                <a href="{{ route('user.done', ['username' => $user->username]) }}">
                    <img class="rounded-circle avatar-20 ml-2 mr-1" src="{{ $user->avatar }}" />
                    <span class="align-middle">
                        @if ($user->firstname or $user->lastname)
                            {{ $user->firstname }}{{ ' '.$user->lastname }}
                        @else
                            {{ $user->username }}
                        @endif
                    </span>
                </a>
            </span>
            @if ($type === "App\Notifications\TaskPraised")
                <span class="align-middle">praised your task</span>
                <div class="font-weight-bold mt-2">
                    <a class="text-dark" href="{{ route('task', ['id' => $data['task_id']]) }}">
                        {{ $data['task'] }}
                    </a>
                </div>
            @elseif ($type === "App\Notifications\TaskMentioned")
                <span class="align-middle">mentioned you in a task</span>
                <div class="font-weight-bold mt-2">
                    <a class="text-dark" href="{{ route('task', ['id' => $data['task_id']]) }}">
                        {{ $data['task'] }}
                    </a>
                </div>
            @elseif ($type === "App\Notifications\TaskCommentPraised")
                <span class="align-middle">praised your task comment</span>
                <div class="font-weight-bold mt-2">
                    <a class="text-dark" href="{{ route('task', ['id' => $data['task_id']]) }}">
                        {{ $data['comment'] }}
                    </a>
                </div>
            @elseif ($type === "App\Notifications\QuestionPraised")
                <span class="align-middle">praised your question</span>
                <div class="font-weight-bold mt-2">
                    <a class="text-dark" href="{{ route('question.question', ['id' => $data['question_id']]) }}">
                        {{ $data['question'] }}
                    </a>
                </div>
            @elseif ($type === "App\Notifications\AnswerPraised")
                <span class="align-middle">praised your answer</span>
                <div class="font-weight-bold mt-2">
                    <a class="text-dark" href="{{ route('question.question', ['id' => $data['question_id']]) }}">
                        {{ Str::words($data['answer'], '15') }}
                    </a>
                </div>
            @elseif ($type === "App\Notifications\TaskCommented")
                <span class="align-middle">commented on your task</span>
                <div class="font-weight-bold mt-2">
                    <a class="text-dark" href="{{ route('task', ['id' => $data['task_id']]) }}">
                        @markdown(Str::words($data['comment'], '15'))
                    </a>
                </div>
            @elseif ($type === "App\Notifications\Answered")
                <span class="align-middle">answered to your question</span>
                <div class="font-weight-bold mt-2">
                    <a class="text-dark" href="{{ route('question.question', ['id' => $data['question_id']]) }}">
                        @markdown(Str::words($data['answer'], '15'))
                    </a>
                </div>
            @elseif ($type === "App\Notifications\Followed")
                <span class="align-middle">followed you</span>
                <div class="mt-2">
                    @livewire('notification.follow', [
                        'user' => $user
                    ])
                </div>
            @elseif ($type === "App\Notifications\Subscribed")
                <span class="align-middle">
                    subscribed to your product
                    <a class="font-weight-bold" href="{{ route('product.done', ['slug' => \App\Product::find($data['product_id'])->slug]) }}">
                        <img class="rounded avatar-20 ml-2 mr-1" src="{{ \App\Product::find($data['product_id'])->avatar }}" />
                        {{ \App\Product::find($data['product_id'])->name }}
                    </a>
                </span>
            @endif
            <div class="small mt-2 text-secondary">
                {{ Carbon::createFromTimeStamp(strtotime($created_at))->diffForHumans() }}
            </div>
        </div>
    </div>
</div>

resources/views/livewire/notification/unread.blade.php
<div>
    @if ($notifications->count() === 0)
    <div class="card-body text-center mt-5">
        <i class="fa fa-4x fa-bell mb-3 text-primary"></i>
        <div class="h4">
            No new notifications
        </div>
    </div>
    @endif
    @foreach ($notifications as $notification)
        <div wire:poll>
            @livewire('notification.single-notification', [
                'type' => $notification->type,
                'data' => $notification->data,
                'created_at' => $notification->created_at,
            ], key($notification->id))
        </div>
    @endforeach
    @if ($notifications->hasMorePages())
        @livewire('notification.load-more', [
            'type' => 'unread',
            'page' => $page,
            'perPage' => $perPage
        ])
    @endif
</div>