routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', 'HomeController@index')->name('home');

Route::group(['prefix' => '@{username}', 'as' => 'user.'], function () {
    Route::get('', 'UserController@done')->name('done');
    Route::get('pending', 'UserController@pending')->name('pending');
    Route::get('products', 'UserController@products')->name('products');
    Route::get('questions', 'UserController@questions')->name('questions');
    Route::get('answers', 'UserController@answers')->name('answers');
    Route::get('following', 'UserController@following')->name('following');
    Route::get('followers', 'UserController@followers')->name('followers');
});

Route::group(['prefix' => 'settings', 'as' => 'user.settings.', 'middleware' => ['auth', 'password.confirm']], function () {
    Route::get('', 'UserController@profileSettings')->name('profile');
    Route::get('account', 'UserController@accountSettings')->name('account');
    Route::get('password', 'UserController@passwordSettings')->name('password');
    Route::get('notifications', 'UserController@notificationsSettings')->name('notifications');
    Route::get('delete', 'UserController@deleteSettings')->name('delete');
});

Route::get('login/{provider}', 'SocialController@redirect');
Route::get('login/{provider}/callback', 'SocialController@Callback');

Route::group(['prefix' => 'product/{slug}', 'as' => 'product.'], function () {
    Route::get('', 'ProductController@done')->name('done');
    Route::get('pending', 'ProductController@pending')->name('pending');
    Route::get('edit', 'ProductController@edit')->name('edit')->middleware('auth');
});

Route::group(['prefix' => 'products', 'as' => 'products.'], function () {
    Route::get('', 'ProductController@newest')->name('newest');
    Route::get('launched', 'ProductController@launched')->name('launched');
    Route::get('new', 'ProductController@new')->name('new')->middleware('auth');
});

Route::group(['prefix' => 'questions', 'as' => 'questions.'], function () {
    Route::get('', 'QuestionController@newest')->name('newest');
    Route::get('unanswered', 'QuestionController@unanswered')->name('unanswered');
    Route::get('popular', 'QuestionController@popular')->name('popular');
    Route::get('new', 'QuestionController@new')->name('new')->middleware('auth');
});

Route::group(['prefix' => 'question', 'as' => 'question.'], function () {
    Route::get('{id}', 'QuestionController@question')->name('question');
    Route::get('edit/{id}', 'QuestionController@edit')->name('edit')->middleware('auth');
});

Route::group(['prefix' => 'notifications', 'as' => 'notifications.', 'middleware' => ['auth']], function () {
    Route::get('', 'NotificationController@unread')->name('unread');
    Route::get('all', 'NotificationController@all')->name('all');
});

// Toggles
Route::get('adminbar', 'Admin\AdminBarController@toggle')->name('adminbar')->middleware(['auth', 'staff']);
Route::get('darkmode', 'UserController@darkMode')->name('darkmode')->middleware('patron');

Route::get('task/{id}', 'TaskController@task')->name('task');

Route::get('tasks', 'TaskController@tasks')->name('tasks')->middleware('auth');

Route::get('patron', 'PatronController@patron')->name('patron');

Route::personalDataExports('personal-data-exports');

Route::get('streaks/{username}', 'StatsController@streaks')->name('streak');

app/Question.php
<?php

namespace App;

use CyrildeWit\EloquentViewable\Contracts\Viewable;
use CyrildeWit\EloquentViewable\InteractsWithViews;
use Illuminate\Database\Eloquent\Model;
use Rennokki\QueryCache\Traits\QueryCacheable;

class Question extends Model implements Viewable
{
    use QueryCacheable, InteractsWithViews;

    protected $cacheFor = 3600;

    protected $fillable = [
        'user_id',
        'title',
        'body',
    ];

    public function user()
    {
        return $this->belongsTo('App\User');
    }

    public function answer()
    {
        return $this->hasMany('App\Answer');
    }

    public function question_praise()
    {
        return $this->hasMany('App\QuestionPraise');
    }
}

app/Http/Controllers/QuestionController.php
<?php

namespace App\Http\Controllers;

use App\Question;
use Auth;

class QuestionController extends Controller
{
    public function newest()
    {
        $trending = Question::orderByViews()
            ->has('answer')
            ->take(5)
            ->get()
            ->sortByDesc(function ($question) {
                return $question->answer->count();
            });

        return view('questions.newest', [
            'type' => 'questions.newest',
            'trending' => $trending,
        ]);
    }

    public function unanswered()
    {
        $trending = Question::orderByViews()
            ->has('answer')
            ->take(5)
            ->get()
            ->sortByDesc(function ($question) {
                return $question->answer->count();
            });

        return view('questions.unanswered', [
            'type' => 'questions.unanswered',
            'trending' => $trending,
        ]);
    }

    public function popular()
    {
        $trending = Question::orderByViews()
            ->has('answer')
            ->take(5)
            ->get()
            ->sortByDesc(function ($question) {
                return $question->answer->count();
            });

        return view('questions.popular', [
            'type' => 'questions.popular',
            'trending' => $trending,
        ]);
    }

    public function question($id)
    {
        $question = Question::where('id', $id)->firstOrFail();
        views($question)->record();

        return view('question.question', [
            'type' => 'question.question',
            'question' => $question,
        ]);
    }

    public function new()
    {
        return view('question.new');
    }

    public function edit($id)
    {
        $question = Question::where('id', $id)->firstOrFail();

        if (Auth::user()->staffShip or Auth::id() === $question->user_id) {
            return view('question.edit', [
                'question' => $question,
            ]);
        } else {
            return redirect()->route('question.question', [
                'id' => $question->id,
            ]);
        }
    }
}

app/Http/Livewire/Question/CreateQuestion.php
<?php

namespace App\Http\Livewire\Question;

use App\Gamify\Points\QuestionCreated;
use App\Question;
use Auth;
use Livewire\Component;

class CreateQuestion extends Component
{
    public $title;
    public $body;

    public function updated($field)
    {
        if (Auth::check()) {
            $this->validateOnly($field, [
                'title' => 'required|profanity|min:5|max:100',
                'body' => 'required|profanity|min:3|max:10000',
            ],
            [
                'title.profanity' => 'Please check your words!',
                'body.profanity' => 'Please check your words!',
            ]);
        } else {
            session()->flash('error', 'Forbidden!');
        }
    }

    public function submit()
    {
        if (Auth::check()) {
            $validatedData = $this->validate([
                'title' => 'required|profanity|min:5|max:100',
                'body' => 'required|profanity|min:3|max:10000',
            ],
            [
                'title.profanity' => 'Please check your words!',
                'body.profanity' => 'Please check your words!',
            ]);

            if (Auth::user()->isFlagged) {
                return session()->flash('error', 'Your account is flagged!');
            }

            $question = Question::create([
                'user_id' =>  Auth::id(),
                'title' => $this->title,
                'body' => $this->body,
            ]);

            session()->flash('question_created', 'Question has been created!');
            givePoint(new QuestionCreated($question));

            return redirect()->route('question.question', ['id' => $question->id]);
        } else {
            session()->flash('error', 'Forbidden!');
        }
    }

    public function render()
    {
        return view('livewire.question.create-question');
    }
}

app/Http/Livewire/Question/EditQuestion.php
<?php

namespace App\Http\Livewire\Question;

use App\Question;
use Auth;
use Livewire\Component;

class EditQuestion extends Component
{
    public $question;
    public $title;
    public $body;

    public function mount($question)
    {
        $this->question = $question;
        $this->title = $question->title;
        $this->body = $question->body;
    }

    public function updated($field)
    {
        if (Auth::check()) {
            $this->validateOnly($field, [
                'title' => 'required|profanity|min:5|max:100',
                'body' => 'required|profanity|min:3|max:10000',
            ],
            [
                'title.profanity' => 'Please check your words!',
                'body.profanity' => 'Please check your words!',
            ]);
        } else {
            session()->flash('error', 'Forbidden!');
        }
    }

    public function submit()
    {
        if (Auth::check()) {
            $validatedData = $this->validate([
                'title' => 'required|profanity|min:5|max:100',
                'body' => 'required|profanity|min:3|max:10000',
            ],
            [
                'title.profanity' => 'Please check your words!',
                'body.profanity' => 'Please check your words!',
            ]);

            if (Auth::user()->isFlagged) {
                return session()->flash('error', 'Your account is flagged!');
            }

            $question = Question::where('id', $this->question->id)->firstOrFail();

            if (Auth::user()->staffShip or Auth::id() === $question->user_id) {
                $question->title = $this->title;
                $question->body = $this->body;
                $question->save();

                session()->flash('question_edited', 'Question has been edited!');

                return redirect()->route('question.question', ['id' => $question->id]);
            } else {
                session()->flash('error', 'Forbidden!');
            }
        } else {
            session()->flash('error', 'Forbidden!');
        }
    }

    public function render()
    {
        return view('livewire.question.edit-question');
    }
}

app/Http/Livewire/Questions/LoadMore.php
<?php

namespace App\Http\Livewire\Questions;

use App\Question;
use Illuminate\Pagination\LengthAwarePaginator;
use Illuminate\Pagination\Paginator;
use Illuminate\Support\Collection;
use Livewire\Component;

class LoadMore extends Component
{
    public $type;
    public $page;
    public $perPage;
    public $loadMore;

    public function mount($page, $perPage, $type)
    {
        $this->type = $type;
        $this->page = $page + 1; //increment the page
        $this->perPage = $perPage;
        $this->loadMore = false; //show the button
    }

    public function paginate($items, $options = [])
    {
        $page = $this->page ?: (Paginator::resolveCurrentPage() ?: 1);
        $items = $items instanceof Collection ? $items : Collection::make($items);

        return new LengthAwarePaginator($items->forPage($page, $this->perPage), $items->count(), $this->perPage, $page, $options);
    }

    public function loadMore()
    {
        $this->loadMore = true;
    }

    public function render()
    {
        if ($this->loadMore) {
            if ($this->type === 'questions.newest') {
                $questions = Question::cacheFor(60 * 60)
                    ->latest()
                    ->get();
            } elseif ($this->type === 'questions.unanswered') {
                $questions = Question::cacheFor(60 * 60)
                    ->doesntHave('answer')
                    ->latest()
                    ->get();
            } elseif ($this->type === 'questions.popular') {
                $questions = Question::cacheFor(60 * 60)
                    ->has('answer')
                    ->get()
                    ->sortByDesc(function ($question) {
                        return $question->answer->count();
                    });
            }

            return view('livewire.questions.questions', [
                'questions' => $this->paginate($questions),
            ]);
        } else {
            return view('livewire.load-more');
        }
    }
}

app/Http/Livewire/Questions/Questions.php
<?php

namespace App\Http\Livewire\Questions;

use App\Question;
use Illuminate\Pagination\LengthAwarePaginator;
use Illuminate\Pagination\Paginator;
use Illuminate\Support\Collection;
use Livewire\Component;

class Questions extends Component
{
    public $type;
    public $page;
    public $perPage;

    public function mount($page, $perPage, $type)
    {
        $this->type = $type;
        $this->page = $page ? $page : 1;
        $this->perPage = $perPage ? $perPage : 1;
    }

    public function paginate($items, $options = [])
    {
        $page = $this->page ?: (Paginator::resolveCurrentPage() ?: 1);
        $items = $items instanceof Collection ? $items : Collection::make($items);

        return new LengthAwarePaginator($items->forPage($page, $this->perPage), $items->count(), $this->perPage, $page, $options);
    }

    public function render()
    {
        if ($this->type === 'questions.newest') {
            $questions = Question::cacheFor(60 * 60)
                ->latest()
                ->get();
        } elseif ($this->type === 'questions.unanswered') {
            $questions = Question::cacheFor(60 * 60)
                ->doesntHave('answer')
                ->latest()
                ->get();
        } elseif ($this->type === 'questions.popular') {
            $questions = Question::cacheFor(60 * 60)
                ->has('answer')
                ->get()
                ->sortByDesc(function ($question) {
                    return $question->answer->count();
                });
        }

        return view('livewire.questions.questions', [
            'questions' => $this->paginate($questions),
            'page' => $this->page,
        ]);
    }
}

app/Http/Livewire/Questions/SingleQuestion.php
<?php

namespace App\Http\Livewire\Questions;

use App\Gamify\Points\PraiseCreated;
use App\Notifications\QuestionPraised;
use App\QuestionPraise;
use Auth;
use Livewire\Component;

class SingleQuestion extends Component
{
    public $question;
    public $type;
    public $confirming;

    public function mount($question, $type)
    {
        $this->question = $question;
        $this->type = $type;
    }

    public function togglePraise()
    {
        if (Auth::check()) {
            if (Auth::user()->isFlagged) {
                return session()->flash('error', 'Your account is flagged!');
            }
            if (Auth::id() === $this->question->user->id) {
                return session()->flash('error', 'You can\'t praise your own question!');
            }
            $isPraised = QuestionPraise::where([
                ['user_id', Auth::id()],
                ['question_id', $this->question->id],
            ])->count();
            if ($isPraised === 1) {
                $praise = QuestionPraise::where([
                    ['user_id', Auth::id()],
                    ['question_id', $this->question->id],
                ])->first();
                $praise->delete();
                $this->question->refresh();
            } else {
                $praise = QuestionPraise::create([
                    'user_id' => Auth::id(),
                    'question_id' => $this->question->id,
                ]);
                $this->question->refresh();
                $this->question->user->notify(new QuestionPraised($this->question, Auth::id()));
                givePoint(new PraiseCreated($praise));
            }
        } else {
            return session()->flash('error', 'Forbidden!');
        }
    }

    public function confirmDelete()
    {
        $this->confirming = $this->question->id;
    }

    public function deleteQuestion()
    {
        if (Auth::check()) {
            if (Auth::user()->isFlagged) {
                return session()->flash('error', 'Your account is flagged!');
            }

            if (Auth::user()->staffShip or Auth::id() === $this->question->user_id) {
                $this->question->delete();
                session()->flash('question_deleted', 'Question has been deleted!');

                return redirect()->route('questions.newest');
            } else {
                session()->flash('error', 'Forbidden!');
            }
        } else {
            return session()->flash('error', 'Forbidden!');
        }
    }

    public function render()
    {
        return view('livewire.questions.single-question');
    }
}

app/Http/Livewire/User/Questions.php
<?php

namespace App\Http\Livewire\User;

use App\Question;
use Livewire\Component;

class Questions extends Component
{
    public $user_id;

    public function mount($user)
    {
        $this->user_id = $user->id;
    }

    public function render()
    {
        $questions = Question::cacheFor(60 * 60)
            ->where('user_id', $this->user_id)
            ->latest()
            ->paginate(20);

        return view('livewire.user.questions', [
            'questions' => $questions,
        ]);
    }
}

resources/views/questions/nav.blade.php
<div class="mb-3">
    <a class="mb-2 btn btn-{{ Route::currentRouteName() === 'questions.newest' ? '' : 'outline-' }}primary mr-2" href="{{ route('questions.newest') }}">
        Newest
    </a>
    <a class="mb-2 btn btn-{{ Route::currentRouteName() === 'questions.unanswered' ? '' : 'outline-' }}primary mr-2" href="{{ route('questions.unanswered') }}">
        Unanswered
    </a>
    <a class="mb-2 btn btn-{{ Route::currentRouteName() === 'questions.popular' ? '' : 'outline-' }}primary mr-2" href="{{ route('questions.popular') }}">
        Popular
    </a>
    <a class="btn btn-success float-md-right mb-2 text-white" href="{{ route('questions.new') }}">
        <i class="fa fa-plus"></i>
        Ask a Question
    </a>
</div>

resources/views/questions/newest.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="container">
            <div class="row">
                <div class="col-md-8">
                    @include('questions.nav')
                    @if (session()->has('question_deleted'))
                        <div class="alert alert-success alert-dismissible fade show mt-2">
                            <button type="button" class="close" data-dismiss="alert">×</button>
                            <i class="fa fa-check mr-1"></i>
                            {{ session('question_deleted') }}
                        </div>
                    @endif
                    @livewire('questions.questions', [
                        'type' => $type,
                        'page' => 1,
                        'perPage' => 10
                    ])
                </div>
                <div class="col-sm">
                    @include('questions.sidebar')
                    @include('components.footer')
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/questions/popular.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="container">
            <div class="row">
                <div class="col-md-8">
                    @include('questions.nav')
                    @livewire('questions.questions', [
                        'type' => $type,
                        'page' => 1,
                        'perPage' => 10
                    ])
                </div>
                <div class="col-sm">
                    @include('questions.sidebar')
                    @include('components.footer')
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/questions/sidebar.blade.php
<div class="card mb-4">
    <div class="card-header">
        <i class="fa fa-fire text-danger mr-1"></i>
        Trending
    </div>
    <ul class="list-group list-group-flush">
        @foreach ($trending as $question)
        <li class="d-flex list-group-item align-items-center justify-content-between">
            <div>
                <a href="{{ route('question.question', ['id' => $question->id]) }}" class="align-text-top text-dark">
                    <span class="font-weight-bold">
                        {{ Str::words($question->title, '10') }}
                    </span>
                </a>
                <div class="text-secondary small mt-1">
                    <i class="fa fa-eye mr-1"></i>
                    <span class="font-weight-bold">{{ views($question)->remember()->unique()->count() }}</span>
                    {{ views($question)->remember()->unique()->count() <= 1 ? 'View' : 'Views' }}
                </div>
            </div>
            <img class="rounded-circle avatar-30 ml-3 float-right" src="{{ $question->user->avatar }}" />
        </li>
        @endforeach
    </ul>
</div>

resources/views/questions/unanswered.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="container">
            <div class="row">
                <div class="col-md-8">
                    @include('questions.nav')
                    @livewire('questions.questions', [
                        'type' => $type,
                        'page' => 1,
                        'perPage' => 10
                    ])
                </div>
                <div class="col-sm">
                    @include('questions.sidebar')
                    @include('components.footer')
                </div>
            </div>
        </div>
    </div>
</div>
@endsection